imports:
    - { resource: "@Tavy315SyliusSalesRepresentativesPlugin/Resources/config/app/grids.yaml" }
    - { resource: "@Tavy315SyliusSalesRepresentativesPlugin/Resources/config/app/sylius_ui.yaml" }
    - { resource: "@Tavy315SyliusSalesRepresentativesPlugin/Resources/config/app/jms_serializer.yaml" }
