sylius_grid:
    templates:
        action:
            tavy315_sylius_sales_representatives_default: "@Tavy315SyliusSalesRepresentativesPlugin/Admin/Grid/Action/tavy315_sylius_sales_representatives_default.html.twig"
    grids:
        tavy315_sylius_sales_representatives_admin_sales_representative:
            driver:
                options:
                    class: "%tavy315_sylius_sales_representatives.model.sales_representative.class%"
            fields:
                code:
                    type: string
                    label: tavy315_sylius_sales_representatives.ui.code
                    sortable: ~
                name:
                    type: string
                    label: tavy315_sylius_sales_representatives.ui.name
                    sortable: ~
                email:
                    type: string
                    label: tavy315_sylius_sales_representatives.ui.email
                    sortable: false
                phoneNumber:
                    type: string
                    label: tavy315_sylius_sales_representatives.ui.phone_number
                    sortable: false
            filters:
                name:
                    type: string
                    label: tavy315_sylius_sales_representatives.ui.name
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
